//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MvcAdvance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;  
    public partial class Employee
    {
        [Required(ErrorMessage ="Field requied")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Field requied")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Field requied")]
        public Nullable<int> Age { get; set; }

        [Required(ErrorMessage = "Field requied")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Field requied")]

        public string Phone { get; set; }

        [Required(ErrorMessage = "Field requied")]
        public string City { get; set; }
    }
}
