// <auto-generated />
namespace CODEFIRST.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Shop3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Shop3));
        
        string IMigrationMetadata.Id
        {
            get { return "202003210803366_Shop3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
